### PR TITLE
User database

### PR DESCRIPTION
**Pull request by CiaraAnderson**
# Problem

Needed to set up Post, Comment and Beer Models and Modify User Model to match the [agreed upon data model](https://docs.google.com/spreadsheets/d/1AcLLbQXGiRlMiPSJS3QMC1iywnJ8-0EoJIvEEaNoklY/edit#gid=0).

# Solution
Created models and associated relationships. Did not add photo as a field of Post as it may be better to create Photo Model for use with CarrierWave.

### CODE REVIEW

**Comment by CiaraAnderson** [comment]
Great, I'll edit those this evening!

**Comment by CiaraAnderson** [comment]
Ok, updated those fields. I left in the sip.rb file etc for now as they were there before, but I'm thinking we can remove those as the post.rb file probably covers that now? My mentor said it shouldn't make any difference leaving it there for now.

**Comment by CiaraAnderson** [comment]
You're right, apologies. Just fixed it.

**Comment by devinjordao** [comment]
The sipz thing was added by Raya I believe when she was setting up tests. We don’t need it though since we have posts like you said so we just need to get rid of it.

Also I don’t think we need to implement “has_many :users” in the beer model because it doesn’t really belong to users, I think just having beers “belong_to :posts” is good.

**Comment by Marshall337** [comment]
You're right @devinjordao, my mistake - beer model doesn't need "has_many users"

I made a clone of Eskil's branch and ended up putting in this for beer model:

belongs_to :user, optional: true
and has_many :posts

I'm having posts belong to beers in my code, since that's going to allow multiple posts for a single beer.

Just put up the PR if you want to check out the rest. I cleaned up some additional stuff, like making beers#index the root of the app.

**Comment by CiaraAnderson** [comment]
Just wanted to leave a quick note for reference before reviewing this later today. On the beer has_many posts as opposed to belongs_to posts issue - that was actually something my mentor and I had gone through. A beer belonging to a post suggests a one-to-one relationship. The documentation says that "if your application includes authors and books, and each book can be assigned to exactly one author, you'd declare the book model this way: class Book belongs_to :author. But our beers won't belong to only one post, they'll belong to many. So, even though it's counter-intuitive a beer "having many" posts might make more sense. As link says that refers to 0 or more instances of another model. Open to feedback! Just wanted to mention it. https://guides.rubyonrails.org/association_basics.html

**Comment by CiaraAnderson** [comment]
Modified beer and user models. Removed Sipz models. Feel free to merge to master if all is good!

**Comment by Marshall337** [comment]
Looks good to go!

**Pull request merged**
