### PR TITLE
Video-Upload for beer

### PR DESCRIPTION
**Pull request by CiaraAnderson**
Just a rough draft of beer uploads for Raya to look over. Formatting is definitely off! But you'll get an idea of the functionality.

### CODE REVIEW

**Comment by CiaraAnderson** [comment]
Sweet! Good to know. My mentor definitely helped out there.

**Comment by do-wuh** [comment]
Honestly, I didn't think the app would have videos for beers, but I suppose it could.  If added to beers it must have a thumbnail option for the videos, or it will break the index and list pages.

**Comment by rayazanderson** [comment]
I'm actually wondering if you had to do anything with the controllers when you set up your video editor?

**Comment by CiaraAnderson** [comment]
I just double-checked and I didn't alter the controllers! Just to respond to Eskil too, I'm fine with either way  - with just photos or videos too. Just started on it as the team seemed to want it. Let me know if you guys want help with anything on that.

**Comment by rayazanderson** [comment]
I guess that sounds good, it seems like you covered the video parts without me haha. I'm going to approve the merge.

**Comment by CiaraAnderson** [comment]
Haha, ok I didn't even really intend to necessarily use this! Was just playing around with it. But if you think it'll work I'm fine with that. There is the issue of it not showing up well as a thumbnail on the home page? Do you think it will mess up the formatting?

**Comment by rayazanderson** [comment]
I think as long as function works, that's good. If there's a way with eskil's help that we can fix the thumbnail issue that would be really helpful.

**Comment by CiaraAnderson** [comment]
ok, maybe we can run it past Eskil and make sure the merge won't break anything/check if he could make that work?

**Comment by rayazanderson** [comment]
Honestly sounds good to me since he's had to tinker the routings a lot this project and his UI is completely unique to him.

**Comment by do-wuh** [comment]
> ok, maybe we can run it past Eskil and make sure the merge won't break anything/check if he could make that work?

The layout is a bit broken at the moment and would prefer not to break the master branch. Let me see what I can do with this branch before we merge it.

**Comment by rayazanderson** [comment]
Sounds good, when you feel the layouts are good lmk so I can try the drag and drop functions again

**Comment by CiaraAnderson** [comment]
Sounds good!

**Comment by do-wuh** [comment]
> Sounds good, when you feel the layouts are good lmk so I can try the drag and drop functions again

got it

**Comment by do-wuh** [comment]
OK, pushed layout changes to this branch. Unfortunately, I'm not sure how to fix the video sizing.  If you click the video on the index page it will go to the beer page, but the video stays the same size until you refresh.
Perhaps you guys can figure something out, before we push to the master.

**Comment by do-wuh** [comment]
whoops, for got to commit
and fixed the video sizing issue

please review

**Comment by do-wuh** [comment]
Do any of you know if there's a way to have one of the frames in the video be a thumbnail? Otherwise the index will have a bunch of black play buttons.

**Comment by CiaraAnderson** [comment]
Hey, when I try to add a video to a new beer I'm getting this error. Not one I've seen before, any ideas of a fix?
Screen Shot 2019-11-14 at 15 43 57

**Comment by do-wuh** [comment]
> Hey, when I try to add a video to a new beer I'm getting this error. Not one I've seen before, any ideas of a fix? Edit: Just pulled your updates Eskil! Testing them out
> Screen Shot 2019-11-14 at 15 43 57

try resetting and pulling it again

**Comment by do-wuh** [comment]
made some slight adjustments to the video preview

**Pull request merged**
