### PR TITLE
Preliminary code for image uploading

### PR DESCRIPTION
**Pull request by CiaraAnderson**
- I have made some of the preliminary code changes for image uploading. Changes include permitting :picture in beer and posts controllers, editing the new.html.erb page in Views and editing the Beers#index page. We don't seem to have a posts#index page. 

 - However, I having trouble with the database migrations. Just uploading this for Raya to have a quick look over before I talk to my mentor, so I'm aware this is not ready to go.
I've tried:         rails g migration add_picture_to_beers picture:beers
But that's giving the error:   PG::UndefinedObject: ERROR:  type "beer" does not exist
LINE 1: ALTER TABLE "beers" ADD "picture" beer

 - Once migrations are figured out, I have the AWS account/keys ready to go for hosting on Heroku.

### CODE REVIEW

**Comment by CiaraAnderson** [comment]
- Can upload beer pic but having issues with beer pic showing up. 
 - Had to use f.file_field instead of f.input in views/beers/new.html.erb to get it working

**Comment by CiaraAnderson** [comment]
- You can currently add beer and post pics. But the post pics are not showing. Some issues on the index page with overlapping pics that I haven't worked out yet.

**Comment by CiaraAnderson** [comment]
- AWS included on this one 

- You might need to run a bundle install before checking this. 

- I also ran into an error with "the difference between the current request and the current time is too large". That can be fixed by running this: sudo ntpdate ntp.ubuntu.com        Third comment here: https://stackoverflow.com/questions/4770635/s3-error-the-difference-between-the-request-time-and-the-current-time-is-too-la
sudo apt-get install ntp

**Comment by do-wuh** [comment]
unable to test if it's working due to `Missing required arguments: aws_access_key_id, aws_secret_access_key`

**Comment by do-wuh** [comment]
Could you add the file_field for picture to the edit.html as well

**Comment by CiaraAnderson** [comment]
> Could you add the file_field for picture to the edit.html as well

OK, just pushed a new version with that. Do you need me to send you a copy of the AWS keys?

**Comment by do-wuh** [comment]
> OK, just pushed a new version with that. Do you need me to send you a copy of the AWS keys?
Don't know what the best course of action is, I suppose we can test it when we push it to heroku?

**Comment by CiaraAnderson** [comment]
Sweet, thanks!

**Comment by rayazanderson** [comment]
uploader works, just be sure to run `bundle exec figaro install` just to get the application.yml file for the keys.

**Pull request merged**
