### PR TITLE
Adding comments

### PR DESCRIPTION
**Pull request by devinjordao**
Only adds comments to posts, no deleting comments or editing yet

### CODE REVIEW

**Comment by do-wuh** [comment]
Are you going to add anything to this? If not, can I pull and make some styling adjustments?

**Comment by devinjordao** [comment]
i think you could do the styling adjustment, should be fine

**Comment by do-wuh** [comment]
FYI, comment editing is still not working

**Comment by do-wuh** [comment]
beer_post_comment_path routing bug

**Pull request merged**
